---
kind: pipeline
type: docker
name: amd64

steps:
  - name: build
    image: eclipse-temurin:25-jdk-noble
    environment:
      GRADLE_USER_HOME: ~/.gradle
    commands:
      - ./gradlew checkScalafmtAll test
      - ./gradlew prepare
      - echo -n "1.1.$DRONE_BUILD_NUMBER,latest" > .tags
      - echo -n "1.1.$DRONE_BUILD_NUMBER" > ./docker/version

  - name: test Dockerfile
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      dry_run: yes
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      platform: linux/amd64
    when:
      branch: master
      event: push


---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: eclipse-temurin:25-jdk-noble
    environment:
      GRADLE_USER_HOME: ~/.gradle
    commands:
      - ./gradlew checkScalafmtAll test
      - ./gradlew prepare
      - echo -n "1.1.$DRONE_BUILD_NUMBER-arm64,latest-arm64" > .tags
      - echo -n "1.1.$DRONE_BUILD_NUMBER" > ./docker/version

  - name: test Dockerfile
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      dry_run: yes
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      repo: eugenezadyra/luxmed-bot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: docker/Dockerfile
      context: docker/
      platform: linux/arm64
    when:
      branch: master
      event: push
