package com.lbs.server.service

import com.lbs.server.rest.BookingRejectedException
import liquibase.{Contexts, LabelExpression, Liquibase}
import liquibase.database.DatabaseFactory
import liquibase.database.jvm.JdbcConnection
import liquibase.resource.ClassLoaderResourceAccessor
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource

import java.util.UUID

class CancellationReceiptServiceSpec {
  private def fixture(): (CancellationReceiptService, JdbcTemplate) = {
    val source = new DriverManagerDataSource(s"jdbc:h2:mem:${UUID.randomUUID()};DB_CLOSE_DELAY=-1", "sa", "")
    val jdbc = new JdbcTemplate(source)
    jdbc.execute("CREATE TABLE cancellation_receipt(account_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, start_at BIGINT NOT NULL, state VARCHAR(32) NOT NULL, requested_at BIGINT NOT NULL, confirmed_at BIGINT, reviewed_at BIGINT, reviewed_by VARCHAR(128), review_reason VARCHAR(1000), review_action VARCHAR(32), PRIMARY KEY(account_id,reservation_id))")
    jdbc.execute("CREATE TABLE cancellation_receipt_review_audit(audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, start_at BIGINT NOT NULL, old_state VARCHAR(32) NOT NULL, new_state VARCHAR(32) NOT NULL, action VARCHAR(32) NOT NULL, reviewed_by VARCHAR(128) NOT NULL, reason VARCHAR(1000) NOT NULL, reviewed_at BIGINT NOT NULL)")
    for (table <- List("cancellation_receipt", "cancellation_receipt_review_audit")) {
      for ((name, kind) <- List("moved_start_at" -> "BIGINT", "moved_end_at" -> "BIGINT",
          "moved_clinic_id" -> "BIGINT", "moved_telemedicine" -> "BOOLEAN",
          "moved_clinic_address" -> "VARCHAR(512)", "moved_clinic_city" -> "VARCHAR(255)",
          "moved_acknowledged_at" -> "BIGINT"))
        jdbc.execute(s"ALTER TABLE $table ADD COLUMN $name $kind")
    }
    (new CancellationReceiptService(jdbc), jdbc)
  }

  @Test def pendingAndReviewedReceiptsSurviveServiceRecreation(): Unit = {
    val (service, jdbc) = fixture()
    service.begin(1L, 77L, 1791288000000L)
    assertTrue(new CancellationReceiptService(jdbc).hasPending(1L))
    assertThrows(classOf[BookingRejectedException], () => service.begin(1L, 77L, 1791288000000L))
    assertThrows(classOf[BookingRejectedException], () => service.begin(1L, 77L, 1791291600000L))
    assertThrows(classOf[BookingRejectedException], () =>
      service.review(1L, 77L, 1791291600000L, "confirmed_cancelled", "operator", "Provider verified"))
    assertTrue(service.hasPending(1L))
    service.review(1L, 77L, 1791288000000L, "confirmed_cancelled", "operator", "Provider verified")
    val recovered = new CancellationReceiptService(jdbc)
    assertFalse(recovered.hasPending(1L))
    val receipt = recovered.receipts(1L).head
    assertEquals("confirmed", receipt.state)
    assertEquals(receipt.reviewedAt, receipt.confirmedAt)
    assertEquals(Some("operator"), receipt.reviewedBy)
    assertEquals(Some("Provider verified"), receipt.reviewReason)
    assertEquals(Some("confirmed_cancelled"), receipt.reviewAction)
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit WHERE old_state='pending' AND new_state='confirmed' AND reviewed_by='operator'", classOf[java.lang.Long]))
    assertThrows(classOf[BookingRejectedException], () =>
      service.review(1L, 77L, 1791288000000L, "verified_still_reserved", "operator", "Changed mind"))
    assertThrows(classOf[BookingRejectedException], () => service.begin(1L, 77L, 1791288000000L))
    assertEquals(Seq.empty, recovered.receipts(2L))
  }

  @Test def stillReservedReviewReleasesHoldButNeverReplaysDelete(): Unit = {
    val (service, jdbc) = fixture()
    service.begin(1L, 88L, 1791288000000L)
    val reviewed = service.review(1L, 88L, 1791288000000L, "verified_still_reserved", "operator-2", "Visit remains in provider account")
    assertEquals("verified_still_reserved", reviewed.state)
    assertEquals(None, reviewed.confirmedAt)
    assertFalse(service.hasPending(1L))
    assertThrows(classOf[BookingRejectedException], () => service.begin(1L, 88L, 1791288000000L))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit WHERE old_state='pending' AND new_state='verified_still_reserved'", classOf[java.lang.Long]))
  }

  @Test def movedReviewPersistsFullVisitFactsAndRemainsPendingUntilAcknowledged(): Unit = {
    val (service, jdbc) = fixture()
    val original = 1791288000000L
    val moved = MovedReservationFact(original + 86400000L, original + 86400000L + 1800000L,
      Some(23L), false, Some("Street 1"), Some("Warsaw"))
    service.begin(1L, 99L, original)
    val reviewed = service.review(1L, 99L, original, "verified_moved", "operator", "Moved in portal", Some(moved))
    assertEquals("verified_moved", reviewed.state)
    assertEquals(Some(moved.startAt), reviewed.movedStartAt)
    assertEquals(Some(moved.endAt), reviewed.movedEndAt)
    assertEquals(Some(23L), reviewed.movedClinicId)
    assertEquals(None, reviewed.acknowledgedAt)
    assertTrue(new CancellationReceiptService(jdbc).hasPending(1L))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit " +
      "WHERE reservation_id=99 AND moved_start_at=? AND moved_end_at=? AND moved_clinic_id=23",
      classOf[java.lang.Long], Long.box(moved.startAt), Long.box(moved.endAt)))
  }

  @Test def auditFailureRollsBackReviewAndRetainsPendingHold(): Unit = {
    val (service, jdbc) = fixture()
    service.begin(1L, 77L, 1791288000000L)
    jdbc.execute("DROP TABLE cancellation_receipt_review_audit")
    assertThrows(classOf[org.springframework.dao.DataAccessException], () =>
      service.review(1L, 77L, 1791288000000L, "confirmed_cancelled", "operator", "Provider verified"))
    assertTrue(service.hasPending(1L))
    assertEquals("pending", service.receipts(1L).head.state)
  }

  @Test def migrationReturnsLegacyConfirmedReceiptsToPendingWithAudit(): Unit = {
    val source = new DriverManagerDataSource(s"jdbc:h2:mem:${UUID.randomUUID()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "")
    val jdbc = new JdbcTemplate(source)
    jdbc.execute("CREATE TABLE cancellation_receipt(account_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, start_at BIGINT NOT NULL, state VARCHAR(20) NOT NULL, requested_at BIGINT NOT NULL, confirmed_at BIGINT, PRIMARY KEY(account_id,reservation_id))")
    jdbc.update("INSERT INTO cancellation_receipt VALUES (1,77,1791288000000,'confirmed',100,200)")
    jdbc.update("INSERT INTO cancellation_receipt VALUES (1,88,1791291600000,'pending',101,NULL)")
    val connection = source.getConnection
    try {
      val database = DatabaseFactory.getInstance.findCorrectDatabaseImplementation(new JdbcConnection(connection))
      val migration = new Liquibase("db/changelog/13-cancellation-review.yml", new ClassLoaderResourceAccessor(), database)
      migration.update(new Contexts(), new LabelExpression())
    } finally connection.close()
    assertEquals("pending", jdbc.queryForObject("SELECT state FROM cancellation_receipt WHERE reservation_id=77", classOf[String]))
    assertEquals(null, jdbc.queryForObject("SELECT confirmed_at FROM cancellation_receipt WHERE reservation_id=77", classOf[java.lang.Long]))
    assertEquals("pending", jdbc.queryForObject("SELECT state FROM cancellation_receipt WHERE reservation_id=88", classOf[String]))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit WHERE reservation_id=77 AND old_state='confirmed' AND new_state='pending' AND action='legacy_unverified' AND reviewed_by='migration'", classOf[java.lang.Long]))
  }

  @Test def pendingCancellationBlocksEveryProviderConfirmationMethod(): Unit = {
    val (receipts, _) = fixture()
    receipts.begin(1L, 77L, 1791288000000L)
    val api = new ApiService()
    val receiptsField = classOf[ApiService].getDeclaredField("cancellationReceipts")
    receiptsField.setAccessible(true)
    receiptsField.set(api, receipts)
    val fenceField = classOf[ApiService].getDeclaredField("bookingFence")
    fenceField.setAccessible(true)
    fenceField.set(api, new AccountBookingFence())
    assertTrue(api.reservationConfirm(1L, null, null).left.toOption.get.isInstanceOf[BookingRejectedException])
    assertTrue(api.reservationChangeTerm(1L, null, null).left.toOption.get.isInstanceOf[BookingRejectedException])
  }
}
