package com.lbs.server.rest

import com.lbs.api.json.model.{AdditionalData, Doctor, Event, EventClinic, LuxmedFunnyDateTime, RelatedVisit, ReservationConfirmResponse, ReservationConfirmValue, ReservationLocktermResponse, ReservationLocktermResponseValue, Term, TermExt, Valuation, XsrfToken}
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.*
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.jdbc.datasource.{DataSourceTransactionManager, DriverManagerDataSource}
import java.util.UUID
import java.time.{LocalDateTime, LocalTime, ZoneId, ZonedDateTime}
import com.lbs.server.repository.model.Monitoring
import com.lbs.server.repository.DataRepository
import com.lbs.bot.model.{MessageSource, MessageSourceSystem}
import com.lbs.server.service.{AccountBookingFence, ApiService, CancellationReceiptService, DataService, MonitoringService}
import org.mockito.ArgumentMatchers.{any, anyLong}
import org.mockito.Mockito.{mock, when}

class BookingAttemptServiceSpec {
  private def fixtureWithDb(): (BookingAttemptService, JdbcTemplate) = {
    val source = new DriverManagerDataSource(s"jdbc:h2:mem:${UUID.randomUUID()};DB_CLOSE_DELAY=-1", "sa", "")
    val jdbc = new JdbcTemplate(source)
    jdbc.execute("CREATE TABLE booking_attempt(id VARCHAR(36) PRIMARY KEY, account_id BIGINT NOT NULL, fingerprint VARCHAR(64) NOT NULL, state VARCHAR(20) NOT NULL, reservation_id BIGINT, error_code VARCHAR(64), created_at BIGINT NOT NULL, phase VARCHAR(24), process_id VARCHAR(36), start_at BIGINT, end_at BIGINT, clinic_id BIGINT, service_id BIGINT, schedule_id BIGINT, doctor_id BIGINT, telemedicine BOOLEAN, baseline_reservation_ids TEXT, baseline_reservation_facts TEXT, acknowledged_at BIGINT)")
    jdbc.execute("CREATE TABLE booking_attempt_review_audit(audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL, attempt_id VARCHAR(36) NOT NULL, fingerprint VARCHAR(64) NOT NULL, reservation_id BIGINT NOT NULL, start_at BIGINT NOT NULL, end_at BIGINT NOT NULL, clinic_id BIGINT NOT NULL, service_id BIGINT NOT NULL, schedule_id BIGINT NOT NULL, doctor_id BIGINT NOT NULL, telemedicine BOOLEAN NOT NULL, baseline_reservation_ids TEXT NOT NULL, service_and_doctor_verified BOOLEAN NOT NULL, provider_request_settled BOOLEAN NOT NULL, reviewed_by VARCHAR(128) NOT NULL, reason VARCHAR(1000) NOT NULL, reviewed_at BIGINT NOT NULL)")
    jdbc.execute("CREATE TABLE booking_account_lock(account_id BIGINT PRIMARY KEY, attempt_id VARCHAR(36) NOT NULL)")
    jdbc.execute("CREATE TABLE legacy_booking_barrier(id VARCHAR(36) PRIMARY KEY, account_id BIGINT NOT NULL, state VARCHAR(20) NOT NULL, reservation_id BIGINT, monitoring_id BIGINT, start_at BIGINT NOT NULL, created_at BIGINT NOT NULL, phase VARCHAR(24), process_id VARCHAR(36))")
    jdbc.execute("CREATE TABLE smart_booking_enrollment(account_id BIGINT PRIMARY KEY, identity_key VARCHAR(255) NOT NULL UNIQUE, enrolled_at BIGINT NOT NULL)")
    jdbc.execute("CREATE TABLE monitoring(record_id BIGINT PRIMARY KEY, account_id BIGINT NOT NULL, active BOOLEAN NOT NULL, autobook BOOLEAN NOT NULL)")
    jdbc.execute("CREATE TABLE credentials(account_id BIGINT NOT NULL, username VARCHAR(255) NOT NULL)")
    jdbc.execute("CREATE TABLE cancellation_receipt(account_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, start_at BIGINT NOT NULL, state VARCHAR(32) NOT NULL, requested_at BIGINT NOT NULL, confirmed_at BIGINT, reviewed_at BIGINT, reviewed_by VARCHAR(128), review_reason VARCHAR(1000), review_action VARCHAR(32), PRIMARY KEY(account_id,reservation_id))")
    jdbc.execute("CREATE TABLE cancellation_receipt_review_audit(audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, account_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, start_at BIGINT NOT NULL, old_state VARCHAR(32) NOT NULL, new_state VARCHAR(32) NOT NULL, action VARCHAR(32) NOT NULL, reviewed_by VARCHAR(128) NOT NULL, reason VARCHAR(1000) NOT NULL, reviewed_at BIGINT NOT NULL, provider_request_settled BOOLEAN NOT NULL DEFAULT FALSE, cancellation_status_verified BOOLEAN NOT NULL DEFAULT FALSE)")
    for (table <- List("cancellation_receipt", "cancellation_receipt_review_audit")) {
      for ((name, kind) <- List("moved_start_at" -> "BIGINT", "moved_end_at" -> "BIGINT",
          "moved_clinic_id" -> "BIGINT", "moved_telemedicine" -> "BOOLEAN",
          "moved_clinic_address" -> "VARCHAR(512)", "moved_clinic_city" -> "VARCHAR(255)",
          "moved_acknowledged_at" -> "BIGINT"))
        jdbc.execute(s"ALTER TABLE $table ADD COLUMN $name $kind")
    }
    jdbc.update("INSERT INTO credentials(account_id,username) VALUES (?,?)", Long.box(1L), "person@example.com")
    (new BookingAttemptService(jdbc, new DataSourceTransactionManager(source), new CancellationReceiptService(jdbc)), jdbc)
  }
  private def fixture(): BookingAttemptService = fixtureWithDb()._1
  private def request(id: String = UUID.randomUUID().toString): BookRequest =
    BookRequest(1, 2, 2, "Clinic", 3, "First", "Last", "", 4, 5, 6,
      "2026-10-06T12:00:00", "2026-10-06T12:30:00", attemptId = Some(id),
      baselineReservationIds = Some(Nil), baselineReservations = Some(Nil))
  private def runLegacyMonitorBooking(service: BookingAttemptService, api: ApiService): Unit = {
    val monitoring = new Monitoring()
    monitoring.recordId = 10L
    monitoring.accountId = 1L
    monitoring.cityId = 1L
    monitoring.clinicId = 2L
    monitoring.serviceId = 3L
    monitoring.doctorId = 4L
    monitoring.dateFrom = ZonedDateTime.of(2026, 6, 1, 0, 0, 0, 0, ZoneId.of("Europe/Warsaw"))
    monitoring.dateTo = monitoring.dateFrom.plusDays(1)
    monitoring.timeFrom = LocalTime.of(8, 0)
    monitoring.timeTo = LocalTime.of(18, 0)
    monitoring.active = true
    val date = LocalDateTime.of(2026, 6, 1, 10, 0)
    val funnyDate = LuxmedFunnyDateTime(dateTimeLocal = Some(date))
    val doctor = Doctor(Some("dr"), Some(List(4L)), Some("John"), Some(false), Some(1L), 4L, Some("Smith"))
    val term = TermExt(AdditionalData(false, Nil),
      Term(Some("Clinic"), 2L, 3L, funnyDate, funnyDate, doctor, Some(""),
        false, false, false, 1L, 1000L, 100L))
    val data = mock(classOf[DataService])
    when(data.findMonitoring(anyLong(), anyLong())).thenReturn(Some(monitoring))
    when(api.getAvailableTerms(anyLong(), anyLong(), any(), anyLong(), any(), any(), any(), any(), any(), anyLong()))
      .thenReturn(Right(List(term)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    val monitorings = new MonitoringService()
    for ((name, value) <- List(
      "dataService" -> data,
      "apiService" -> api,
      "bookingFence" -> new AccountBookingFence(),
      "bookingAttempts" -> service
    )) {
      val field = classOf[MonitoringService].getDeclaredField(name)
      field.setAccessible(true)
      field.set(monitorings, value)
    }
    val time = java.time.Duration.between(LocalDateTime.of(2022, 1, 1, 0, 0), date).toMinutes
    monitorings.bookAppointmentByScheduleId(1L, 10L, 1000L, time)
  }
  private val success = ReservationConfirmResponse(Nil, Nil, false, false, ReservationConfirmValue(false, "fixture", 77, 88))
  private def controllerWith(service: BookingAttemptService, monitorings: MonitoringService,
                             api: ApiService = null, smartEnrolled: Boolean = true): LuxmedRestController = {
    if (smartEnrolled) service.enrollSmartBooking(1L)
    if (api != null) when(api.reservedVerified(anyLong(), any(), any())).thenReturn(Right(Nil))
    val controller = new LuxmedRestController()
    for ((name, value) <- List(
      "monitoringService" -> monitorings,
      "bookingAttempts" -> service,
      "bookingFence" -> new AccountBookingFence(),
      "apiService" -> api
    )) {
      val field = classOf[LuxmedRestController].getDeclaredField(name)
      field.setAccessible(true)
      field.set(controller, value)
    }
    controller
  }

  @Test def replayReturnsStoredReceiptWithoutAnotherBooking(): Unit = {
    val service = fixture()
    val req = request()
    var calls = 0
    def book() = { calls += 1; Right(success) }
    assertEquals("succeeded", service.execute(1, req)(() => book()).state)
    assertEquals(Some(77L), service.execute(1, req)(() => book()).reservationId)
    assertEquals(1, calls)
    assertTrue(service.status(2, req.attemptId.get).isEmpty)
  }

  @Test def uncertainOutcomeHoldsAccountAndCannotBeRetried(): Unit = {
    val service = fixture()
    val req = request()
    assertEquals("unknown", service.execute(1, req)(() => Left(new java.net.SocketTimeoutException())).state)
    assertEquals("unknown", service.execute(1, req)(() => throw new AssertionError("must not retry")).state)
    val denied = request()
    assertEquals("failed", service.execute(1, denied)(() => throw new AssertionError("account must be held")).state)
    assertEquals(Some("ACCOUNT_BUSY"), service.status(1, denied.attemptId.get).get.errorCode)
    assertTrue(service.accountBusy(1))
  }

  @Test def positiveReviewNeedsExactNewReservationAndOperatorAttestation(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val req = request().copy(baselineReservationIds = Some(List(55L)),
      baselineReservations = Some(List(ReservationBaselineFact(55L, 1791288000000L, 1791289800000L,
        Some(2L), false, Some("Street"), Some("Warsaw")))))
    val id = req.attemptId.get
    assertEquals("unknown", service.execute(1L, req)(() => {
      assertTrue(service.markSmartConfirmationStarted(1L, id).isRight)
      Left(new java.net.SocketTimeoutException("confirmation response lost"))
    }).state)
    val facts = service.reviewContext(1L, id).get
    val start = ZonedDateTime.of(2026, 10, 6, 12, 0, 0, 0, ZoneId.of("Europe/Warsaw"))
    val event = Event(start, Some(EventClinic("Street 1", "Warsaw", Some(2L), Some("Clinic"))), None,
      77L, "Reserved", "Expected service", Some(start.plusMinutes(30)), Some("Visit"))
    val review = BookingPositiveReviewRequest(77L, facts.fingerprint, facts.startAt, facts.endAt,
      facts.clinicId, facts.baselineReservationIds, true, true, "operator", "Provider confirmed the intended visit and request settled")
    assertThrows(classOf[BookingRejectedException], () =>
      service.reviewPositiveAttempt(1L, id, review.copy(providerRequestSettled = false), List(event)))
    assertThrows(classOf[BookingRejectedException], () =>
      service.reviewPositiveAttempt(1L, id, review.copy(expectedBaselineReservationIds = Nil), List(event)))
    assertThrows(classOf[BookingRejectedException], () =>
      service.reviewPositiveAttempt(1L, id, review, List(event.copy(eventId = 55L))))
    assertEquals("succeeded", service.reviewPositiveAttempt(1L, id, review, List(event)).state)
    assertEquals(Some(77L), service.status(1L, id).get.reservationId)
    assertTrue(service.accountBusy(1L))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM booking_attempt_review_audit WHERE attempt_id=?",
      classOf[java.lang.Long], id))
    assertFalse(service.acknowledgeSmartBooking(1L, id, 78L))
    assertTrue(service.accountBusy(1L))
    assertTrue(service.acknowledgeSmartBooking(1L, id, 77L))
    assertTrue(service.acknowledgeSmartBooking(1L, id, 77L))
    assertFalse(service.accountBusy(1L))
  }

  @Test def cancellationPermitIsReleasedOnlyByTheExactReviewedReceipt(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val startAt = 1791288000000L
    val observed = List(Event(ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(startAt), ZoneId.of("Europe/Warsaw")),
      None, None, 77L, "Reserved", "Visit"))
    service.beginCancellation(1L, 77L, startAt)
    assertTrue(service.accountBusy(1L))
    assertThrows(classOf[BookingRejectedException], () =>
      service.reviewCancellation(1L, 77L, 1791288000001L,
        "verified_still_reserved", "operator", "The visit remains reserved", true, false, None, observed))
    assertTrue(service.accountBusy(1L))
    assertEquals("verified_still_reserved", service.reviewCancellation(1L, 77L, startAt,
      "verified_still_reserved", "operator", "The visit remains reserved", true, false, None, observed).state)
    assertFalse(service.accountBusy(1L))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit WHERE reservation_id=77",
      classOf[java.lang.Long]))
    assertThrows(classOf[BookingRejectedException], () => service.beginCancellation(1L, 77L, 1791288000000L))
    assertFalse(service.accountBusy(1L))
  }

  @Test def telemedicineWithNoClinicIdCanBeReviewedByExactVisitTypeAndTime(): Unit = {
    val service = fixture()
    val req = request().copy(clinicId = 0L, isTelemedicine = true)
    val id = req.attemptId.get
    assertEquals("unknown", service.execute(1L, req)(() => {
      assertTrue(service.markSmartConfirmationStarted(1L, id).isRight)
      Left(new java.net.SocketTimeoutException("confirmation response lost"))
    }).state)
    val facts = service.reviewContext(1L, id).get
    val start = ZonedDateTime.of(2026, 10, 6, 12, 0, 0, 0, ZoneId.of("Europe/Warsaw"))
    val event = Event(start, None, None, 77L, "Reserved", "Telemedicine",
      Some(start.plusMinutes(30)), Some("Telemedicine"))
    val review = BookingPositiveReviewRequest(77L, facts.fingerprint, facts.startAt, facts.endAt,
      0L, Nil, true, true, "operator", "Provider confirmed the intended visit and request settled")
    assertEquals("succeeded", service.reviewPositiveAttempt(1L, id, review, List(event)).state)
  }

  @Test def oldAttemptReplayUsesItsOriginalFingerprintWithoutRequiringABaseline(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val oldRequest = request().copy(baselineReservationIds = None)
    val id = oldRequest.attemptId.get
    val oldShape = "BookRequest(1,2,2,Clinic,3,First,Last,,4,5,6,2026-10-06T12:00:00," +
      "2026-10-06T12:30:00,false,false,None,None,false,List(),false,None)"
    val hash = BookingAttemptService.fingerprint(oldShape)
    assertEquals(hash, BookingAttemptService.legacyFingerprint(oldRequest))
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,created_at,phase,process_id) " +
      "VALUES (?,1,?,'unknown',1,'confirmation_started','old-image')", id, hash)
    jdbc.update("INSERT INTO booking_account_lock(account_id,attempt_id) VALUES (1,?)", id)
    assertEquals("unknown", service.execute(1L, oldRequest)(() => throw new AssertionError("no replay")).state)
    assertThrows(classOf[IllegalArgumentException], () =>
      service.execute(1L, oldRequest.copy(serviceId = 99L))(() => throw new AssertionError("no replay")))
    assertTrue(service.accountBusy(1L))
  }

  @Test def acknowledgementAcceptsAnOldSuccessWhoseLockWasAlreadyReleased(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val id = UUID.randomUUID().toString
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,reservation_id,created_at) " +
      "VALUES (?,1,'old-fingerprint','succeeded',77,1)", id)
    assertTrue(service.acknowledgeSmartBooking(1L, id, 77L))
    assertFalse(service.acknowledgeSmartBooking(1L, id, 78L))
    assertFalse(service.accountBusy(1L))
  }

  @Test def v3AttemptReplayKeepsItsIdOnlyFingerprintAfterV4Upgrade(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val oldRequest = request().copy(baselineReservations = None)
    val id = oldRequest.attemptId.get
    val oldShape = "BookRequest(1,2,2,Clinic,3,First,Last,,4,5,6,2026-10-06T12:00:00," +
      "2026-10-06T12:30:00,false,false,None,None,false,List(),false,None,Some(List()))"
    val hash = BookingAttemptService.fingerprint(oldShape)
    assertEquals(hash, BookingAttemptService.v3Fingerprint(oldRequest))
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,created_at,phase,process_id," +
      "start_at,end_at,clinic_id,service_id,schedule_id,doctor_id,telemedicine,baseline_reservation_ids) " +
      "VALUES (?,1,?,'unknown',1,'confirmation_started','old-v3',1791280800000,1791282600000,2,6,5,3,FALSE,'')",
      id, hash)
    jdbc.update("INSERT INTO booking_account_lock(account_id,attempt_id) VALUES (1,?)", id)
    assertEquals("unknown", service.execute(1L, oldRequest)(() => throw new AssertionError("no provider retry")).state)
    assertThrows(classOf[IllegalArgumentException], () => service.execute(1L,
      oldRequest.copy(serviceId = 99L))(() => throw new AssertionError("no provider retry")))
  }

  @Test def postCrashConfirmationCanBeReviewedAfterRestartWithoutReleasingItsLock(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val req = request()
    val id = req.attemptId.get
    val start = ZonedDateTime.of(2026, 10, 6, 12, 0, 0, 0, ZoneId.of("Europe/Warsaw"))
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,created_at,phase,process_id," +
      "start_at,end_at,clinic_id,service_id,schedule_id,doctor_id,telemedicine,baseline_reservation_ids) " +
      "VALUES (?,1,?,'pending',1,'confirmation_started','old-process',?,?,?,?,?,?,FALSE,'')",
      id, BookingAttemptService.fingerprint(req.copy(attemptId = None).toString),
      Long.box(start.toInstant.toEpochMilli), Long.box(start.plusMinutes(30).toInstant.toEpochMilli),
      Long.box(2L), Long.box(6L), Long.box(5L), Long.box(3L))
    jdbc.update("INSERT INTO booking_account_lock(account_id,attempt_id) VALUES (1,?)", id)
    val restarted = new BookingAttemptService(jdbc, new DataSourceTransactionManager(jdbc.getDataSource),
      new CancellationReceiptService(jdbc))
    assertEquals(0, restarted.recoverPreparedAfterRestart())
    assertEquals("unknown", restarted.status(1L, id).get.state)
    assertTrue(restarted.accountBusy(1L))
    val facts = restarted.reviewContext(1L, id).get
    val review = BookingPositiveReviewRequest(77L, facts.fingerprint, facts.startAt, facts.endAt,
      facts.clinicId, Nil, true, true, "operator", "Provider confirmed the intended visit and request settled")
    val event = Event(start, Some(EventClinic("Street 1", "Warsaw", Some(2L), Some("Clinic"))), None,
      77L, "Reserved", "Expected service", Some(start.plusMinutes(30)), Some("Visit"))
    assertEquals("succeeded", restarted.reviewPositiveAttempt(1L, id, review, List(event)).state)
    assertTrue(restarted.accountBusy(1L))
  }

  @Test def restartReleasesOnlyPreparedSmartAndLegacyWork(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val preparedId = UUID.randomUUID().toString
    val confirmedId = UUID.randomUUID().toString
    val oldId = UUID.randomUUID().toString
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,created_at,phase,process_id) VALUES (?,?,?,'pending',1,'prepared','prior-boot')",
      preparedId, Long.box(1L), "fixture")
    jdbc.update("INSERT INTO booking_account_lock(account_id,attempt_id) VALUES (?,?)", Long.box(1L), preparedId)
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,created_at,phase,process_id) VALUES (?,?,?,'pending',1,'confirmation_started','prior-boot')",
      confirmedId, Long.box(2L), "fixture")
    jdbc.update("INSERT INTO booking_account_lock(account_id,attempt_id) VALUES (?,?)", Long.box(2L), confirmedId)
    jdbc.update("INSERT INTO booking_attempt(id,account_id,fingerprint,state,created_at) VALUES (?,?,?,'pending',1)",
      oldId, Long.box(3L), "fixture")
    jdbc.update("INSERT INTO booking_account_lock(account_id,attempt_id) VALUES (?,?)", Long.box(3L), oldId)
    val legacyPrepared = service.beginLegacyBooking(4L, 100L)
    val legacyConfirmed = service.beginLegacyBooking(5L, 100L)
    assertTrue(service.markLegacyConfirmationStarted(5L, legacyConfirmed).isRight)
    val restarted = new BookingAttemptService(jdbc, new DataSourceTransactionManager(jdbc.getDataSource),
      new CancellationReceiptService(jdbc))
    assertEquals(2, restarted.recoverPreparedAfterRestart())
    assertEquals("failed", restarted.status(1L, preparedId).get.state)
    assertEquals(Some("PREPARED_INTERRUPTED"), restarted.status(1L, preparedId).get.errorCode)
    assertFalse(restarted.accountBusy(1L))
    assertEquals("unknown", restarted.status(2L, confirmedId).get.state)
    assertTrue(restarted.accountBusy(2L))
    assertEquals("pending", restarted.status(3L, oldId).get.state)
    assertTrue(restarted.accountBusy(3L))
    assertEquals("clear", restarted.legacyBarrier(4L).state)
    assertEquals("pending", restarted.legacyBarrier(5L).state)
    assertEquals(0, restarted.recoverPreparedAfterRestart())
    assertFalse(service.markLegacyConfirmationStarted(4L, legacyPrepared).isRight)
  }

  @Test def competingProcessRecoveryPreventsSmartConfirmation(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val restarted = new BookingAttemptService(jdbc, new DataSourceTransactionManager(jdbc.getDataSource),
      new CancellationReceiptService(jdbc))
    val api = mock(classOf[ApiService])
    val monitorings = mock(classOf[MonitoringService])
    when(monitorings.getActiveMonitorings(1L)).thenReturn(Seq.empty)
    val controller = controllerWith(service, monitorings, api)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenAnswer(_ => {
      assertEquals(1, restarted.recoverPreparedAfterRestart())
      Right(lock)
    })
    val outcome = controller.submitBookingAttempt(1L, request().copy(isImpediment = Some(false)))
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals("failed", outcome.state)
    assertFalse(service.accountBusy(1L))
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationConfirm(anyLong(), any(), any(), any())
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationChangeTerm(anyLong(), any(), any(), any())
  }

  @Test def confirmationMarkerSurvivesRestartWithoutReleasingTheLock(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val req = request()
    val outcome = service.execute(1L, req)(() => {
      assertTrue(service.markSmartConfirmationStarted(1L, req.attemptId.get).isRight)
      throw new java.net.SocketTimeoutException("confirmation response lost")
    })
    assertEquals("unknown", outcome.state)
    val restarted = new BookingAttemptService(jdbc, new DataSourceTransactionManager(jdbc.getDataSource),
      new CancellationReceiptService(jdbc))
    assertEquals(0, restarted.recoverPreparedAfterRestart())
    assertTrue(restarted.accountBusy(1L))
    assertEquals("unknown", restarted.status(1L, req.attemptId.get).get.state)
  }

  @Test def thrownPreConfirmationSmartWorkReleasesOnlyPreparedAttempt(): Unit = {
    val service = fixture()
    val before = request()
    val failed = service.execute(1L, before)(() => throw new IllegalArgumentException("pre-confirm conversion"))
    assertEquals("failed", failed.state)
    assertEquals(Some("BOOKING_NOT_SUBMITTED"), failed.errorCode)
    assertFalse(service.accountBusy(1L))
    val after = request()
    val unknown = service.execute(1L, after)(() => {
      assertTrue(service.markSmartConfirmationStarted(1L, after.attemptId.get).isRight)
      throw new java.net.SocketTimeoutException("confirmation response lost")
    })
    assertEquals("unknown", unknown.state)
    assertTrue(service.accountBusy(1L))
  }

  @Test def incompleteLegacyLocktermReleasesPreparedBarrier(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(
      Right(ReservationLocktermResponse(Nil, Nil, true, false, null)))
    runLegacyMonitorBooking(service, api)
    assertEquals("clear", service.legacyBarrier(1L).state)
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationConfirm(anyLong(), any(), any(), any())
  }

  @Test def thrownPreConfirmationLegacyCallReleasesPreparedBarrier(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    when(api.reservationLockterm(anyLong(), any(), any())).thenThrow(new IllegalArgumentException("pre-confirm call"))
    runLegacyMonitorBooking(service, api)
    assertEquals("clear", service.legacyBarrier(1L).state)
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationConfirm(anyLong(), any(), any(), any())
  }

  @Test def competingProcessRecoveryPreventsLegacyConfirmation(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val restarted = new BookingAttemptService(jdbc, new DataSourceTransactionManager(jdbc.getDataSource),
      new CancellationReceiptService(jdbc))
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenAnswer(_ => {
      assertEquals(1, restarted.recoverPreparedAfterRestart())
      Right(lock)
    })
    val response = controller.bookAppointment(1L, request().copy(attemptId = None))
    assertNotEquals(200, response.getStatusCode.value())
    assertEquals("clear", service.legacyBarrier(1L).state)
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationConfirm(anyLong(), any(), any(), any())
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationChangeTerm(anyLong(), any(), any(), any())
  }

  @Test def confirmationBusinessErrorWithoutReceiptKeepsAccountLocked(): Unit = {
    val service = fixture()
    assertEquals("unknown", service.execute(1, request())(() => Right(success.copy(hasErrors = true, value = null))).state)
    assertTrue(service.accountBusy(1L))
    assertEquals(Some("ACCOUNT_BUSY"), service.execute(1, request())(() => Right(success)).errorCode)
  }

  @Test def contradictoryErrorWithReservationIdKeepsUnknownAccountLock(): Unit = {
    val service = fixture()
    val outcome = service.execute(1, request())(() => Right(success.copy(hasErrors = true)))
    assertEquals("unknown", outcome.state)
    assertTrue(service.accountBusy(1L))
    val next = service.execute(1, request())(() => throw new AssertionError("must not submit another booking"))
    assertEquals(Some("ACCOUNT_BUSY"), next.errorCode)
  }

  @Test def rejectionErrorAfterConfirmationStartsCannotReleaseAccountLock(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val monitorings = mock(classOf[MonitoringService])
    when(monitorings.getActiveMonitorings(1L)).thenReturn(Seq.empty)
    val controller = controllerWith(service, monitorings, api)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(Right(lock))
    when(api.reservationConfirm(anyLong(), any(), any(), any()))
      .thenReturn(Left(new BookingRejectedException("UPSTREAM_REJECTION_AFTER_SEND")))
    val outcome = controller.submitBookingAttempt(1L, request().copy(isImpediment = Some(false)))
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals("unknown", outcome.state)
    assertTrue(service.accountBusy(1L))
  }

  @Test def attemptCannotBeReusedWithAnotherSlot(): Unit = {
    val service = fixture()
    val req = request()
    service.execute(1, req)(() => Right(success))
    assertThrows(classOf[IllegalArgumentException], () => service.execute(1, req.copy(scheduleId = 99))(() => Right(success)))
  }

  @Test def failureBeforeSubmissionReleasesTheAccount(): Unit = {
    val service = fixture()
    val outcome = service.execute(1, request())(() => Left(new BookingNotSubmittedException(new RuntimeException("login failed"))))
    assertEquals("failed", outcome.state)
    assertEquals(Some("BOOKING_NOT_SUBMITTED"), outcome.errorCode)
    assertEquals("succeeded", service.execute(1, request())(() => Right(success)).state)
  }

  @Test def activeLegacyAutomaticMonitorProducesDurableFailureBeforeLuxmedSubmission(): Unit = {
    val service = fixture()
    val monitorings = mock(classOf[MonitoringService])
    val legacy = new Monitoring()
    legacy.autobook = true
    when(monitorings.getActiveMonitorings(1L)).thenReturn(Seq(legacy))
    val controller = controllerWith(service, monitorings)
    val req = request().copy(isImpediment = Some(false))
    val outcome = controller.submitBookingAttempt(1L, req).getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals("failed", outcome.state)
    assertEquals(Some("LEGACY_AUTO_MONITOR_ACTIVE"), outcome.errorCode)
    assertEquals(outcome, service.status(1L, req.attemptId.get).get)
    assertFalse(service.accountBusy(1L))
  }

  @Test def monitorReadFailureBeforeSubmissionDoesNotHoldTheAccount(): Unit = {
    val service = fixture()
    val monitorings = mock(classOf[MonitoringService])
    when(monitorings.getActiveMonitorings(1L)).thenThrow(new RuntimeException("fixture database outage"))
    val controller = controllerWith(service, monitorings)
    val req = request().copy(isImpediment = Some(false))
    val outcome = controller.submitBookingAttempt(1L, req).getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals("failed", outcome.state)
    assertEquals(Some("BOOKING_NOT_SUBMITTED"), outcome.errorCode)
    assertEquals(outcome, service.status(1L, req.attemptId.get).get)
    assertFalse(service.accountBusy(1L))
  }

  @Test def legacyBookingBarrierBlocksSmartSubmissionUntilItsReceiptIsAcknowledged(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val monitorings = mock(classOf[MonitoringService])
    when(monitorings.getActiveMonitorings(1L)).thenReturn(Seq.empty)
    val controller = controllerWith(service, monitorings)
    val id = UUID.randomUUID().toString
    jdbc.update("INSERT INTO legacy_booking_barrier(id,account_id,state,start_at,created_at,phase,process_id) " +
      "VALUES (?,1,'pending',1791288000000,1,'confirmation_started','older-image')", id)
    assertEquals(LegacyBookingBarrier("pending", None, Some(1791288000000L), Some(id)), service.legacyBarrier(1L))
    val pending = controller.submitBookingAttempt(1L, request().copy(isImpediment = Some(false)))
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals(Some("ACCOUNT_BUSY"), pending.errorCode)
    service.completeLegacyBooking(1L, id, 77L)
    assertEquals(LegacyBookingBarrier("succeeded", Some(77L), Some(1791288000000L), Some(id)), service.legacyBarrier(1L))
    val succeeded = controller.submitBookingAttempt(1L, request().copy(isImpediment = Some(false)))
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals(Some("ACCOUNT_BUSY"), succeeded.errorCode)
    assertEquals(409, controller.acknowledgeLegacyBooking(1L, LegacyBookingAcknowledgeRequest(78L)).getStatusCode.value())
    assertEquals("succeeded", service.legacyBarrier(1L).state)
    assertEquals(200, controller.acknowledgeLegacyBooking(1L,
      LegacyBookingAcknowledgeRequest(77L, Some(id), Some(1791288000000L))).getStatusCode.value())
    assertEquals("clear", service.legacyBarrier(1L).state)
    assertEquals("clear", service.legacyBarrier(2L).state)
  }

  @Test def pendingLegacyBarrierCanOnlyBeClearedBeforeSubmission(): Unit = {
    val service = fixture()
    val early = service.beginLegacyBooking(1L, 1791288000000L)
    service.clearLegacyBeforeSubmission(1L, early)
    assertEquals("clear", service.legacyBarrier(1L).state)
    val unknown = service.beginLegacyBooking(1L, 1791288000000L)
    assertFalse(service.acknowledgeLegacyBooking(1L, unknown, 77L, 1791288000000L))
    assertEquals("pending", service.legacyBarrier(1L).state)
    service.completeLegacyBooking(1L, unknown, 77L)
    assertThrows(classOf[BookingRejectedException], () => service.beginLegacyBooking(1L, 1791374400000L))
    assertTrue(service.acknowledgeLegacyBooking(1L, unknown, 77L, 1791288000000L))
    val second = service.beginLegacyBooking(1L, 1791374400000L)
    assertEquals("pending", service.legacyBarrier(1L).state)
    service.clearLegacyBeforeSubmission(1L, second)
    assertEquals("clear", service.legacyBarrier(1L).state)
  }

  @Test def pendingLegacyOutcomeBlocksAllMonitorsButSuccessBlocksOnlyItsSource(): Unit = {
    val service = fixture()
    val id = service.beginLegacyBooking(1L, 1791288000000L, Some(10L))
    assertFalse(service.canLegacyMonitorBook(1L, 10L))
    assertFalse(service.canLegacyMonitorBook(1L, 11L))
    service.completeLegacyBooking(1L, id, 77L)
    assertFalse(service.canLegacyMonitorBook(1L, 10L))
    assertTrue(service.accountBusy(1L))
    assertFalse(service.canLegacyMonitorBook(1L, 11L))
    assertTrue(service.canLegacyMonitorBook(2L, 10L))
  }

  @Test def oldChatCallbackEntersAccountFenceBeforeAnyBooking(): Unit = {
    val service = fixture()
    class RecordingFence extends AccountBookingFence {
      var calls = 0
      override def withLock[A](accountId: Long)(body: => A): A = {
        calls += 1
        super.withLock(accountId)(body)
      }
    }
    val fence = new RecordingFence()
    val monitoring = new Monitoring()
    monitoring.recordId = 10L
    monitoring.accountId = 1L
    monitoring.cityId = 1L
    monitoring.clinicId = 2L
    monitoring.serviceId = 3L
    monitoring.doctorId = 4L
    monitoring.dateFrom = ZonedDateTime.of(2026, 6, 1, 0, 0, 0, 0, ZoneId.of("Europe/Warsaw"))
    monitoring.dateTo = monitoring.dateFrom.plusDays(1)
    monitoring.timeFrom = LocalTime.of(8, 0)
    monitoring.timeTo = LocalTime.of(18, 0)
    monitoring.active = false // The account fence is still entered before this live-state check.
    val data = mock(classOf[DataService])
    when(data.findMonitoring(anyLong(), anyLong())).thenReturn(Some(monitoring))
    val api = mock(classOf[ApiService])
    val date = LocalDateTime.of(2026, 6, 1, 10, 0)
    val funnyDate = LuxmedFunnyDateTime(dateTimeLocal = Some(date))
    val doctor = Doctor(Some("dr"), Some(List(4L)), Some("John"), Some(false), Some(1L), 4L, Some("Smith"))
    val term = TermExt(AdditionalData(false, Nil),
      Term(Some("Clinic"), 2L, 3L, funnyDate, funnyDate, doctor, Some(""),
        false, false, false, 1L, 1000L, 100L))
    when(api.getAvailableTerms(anyLong(), anyLong(), any(), anyLong(), any(), any(), any(), any(), any(), anyLong()))
      .thenReturn(Right(List(term)))
    val monitorings = new MonitoringService()
    for ((name, value) <- List(
      "dataService" -> data,
      "apiService" -> api,
      "bookingFence" -> fence,
      "bookingAttempts" -> service
    )) {
      val field = classOf[MonitoringService].getDeclaredField(name)
      field.setAccessible(true)
      field.set(monitorings, value)
    }
    val time = java.time.Duration.between(LocalDateTime.of(2022, 1, 1, 0, 0), date).toMinutes
    monitorings.bookAppointmentByScheduleId(1L, 10L, 1000L, time)
    assertEquals(1, fence.calls)
    assertEquals("clear", service.legacyBarrier(1L).state)
  }

  @Test def legacyBookPathRejectsAttemptIdsInsteadOfBypassingSmartChecks(): Unit = {
    val service = fixture()
    val controller = controllerWith(service, mock(classOf[MonitoringService]))
    val req = request()
    assertEquals(400, controller.bookAppointment(1L, req).getStatusCode.value())
    assertTrue(service.status(1L, req.attemptId.get).isEmpty)
  }

  @Test def manualLegacyBookPersistsItsReceiptBeforeReturning(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(Right(lock))
    when(api.reservationConfirm(anyLong(), any(), any(), any())).thenReturn(Right(success))
    val response = controller.bookAppointment(1L, request().copy(attemptId = None))
    assertEquals(200, response.getStatusCode.value())
    assertEquals(Some(77L), service.legacyBarrier(1L).reservationId)
    assertEquals(Some(1791280800000L), service.legacyBarrier(1L).start)
    assertTrue(service.legacyBarrier(1L).id.nonEmpty)
    assertEquals(409, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
  }

  @Test def malformedLegacyVisitEndDoesNotLeaveAPreparedBarrier(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    val invalid = request().copy(attemptId = None, dateTimeTo = "not-a-date")
    assertEquals(500, controller.bookAppointment(1L, invalid).getStatusCode.value())
    assertEquals("clear", service.legacyBarrier(1L).state)
  }

  @Test def thrownPreConfirmationFailureDoesNotLeaveAPreparedBarrier(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    when(api.getXsrfToken(anyLong())).thenThrow(new IllegalStateException("token unavailable"))
    assertEquals(500, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
    assertEquals("clear", service.legacyBarrier(1L).state)
  }

  @Test def thrownConfirmationKeepsLegacyOutcomeUnknown(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(Right(lock))
    when(api.reservationConfirm(anyLong(), any(), any(), any())).thenThrow(new IllegalStateException("response lost"))
    assertEquals(500, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
    assertEquals("pending", service.legacyBarrier(1L).state)
  }

  @Test def lostManualLegacyConfirmationKeepsPendingBarrier(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(Right(lock))
    when(api.reservationConfirm(anyLong(), any(), any(), any()))
      .thenReturn(Left(new java.net.SocketTimeoutException("lost response")))
    controller.bookAppointment(1L, request().copy(attemptId = None))
    assertEquals("pending", service.legacyBarrier(1L).state)
    assertEquals(409, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
  }

  @Test def incompleteManualLegacyReceiptIsNotReportedAsBooked(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api, smartEnrolled = false)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(Right(lock))
    when(api.reservationConfirm(anyLong(), any(), any(), any()))
      .thenReturn(Right(success.copy(hasErrors = true)))
    assertEquals(409, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
    assertEquals("pending", service.legacyBarrier(1L).state)
  }

  @Test def enrollmentPermanentlyFencesOldManualBookPath(): Unit = {
    val service = fixture()
    val controller = controllerWith(service, mock(classOf[MonitoringService]), smartEnrolled = false)
    assertFalse(service.smartBookingEnrolled(1L))
    assertEquals(200, controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(Nil)).getStatusCode.value())
    assertEquals(200, controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(Nil)).getStatusCode.value())
    assertTrue(service.smartBookingEnrolled(1L))
    assertEquals(409, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
    assertFalse(service.canLegacyMonitorBook(1L, 99L))
    assertEquals("clear", service.legacyBarrier(1L).state)
  }

  @Test def enrollmentCapabilityRequiresThePreviewedMonitorSet(): Unit = {
    val controller = controllerWith(fixture(), mock(classOf[MonitoringService]), smartEnrolled = false)
    val capabilities = controller.capabilities().getBody.asInstanceOf[ApiResponse[List[String]]].data.get
    assertTrue(capabilities.contains("smart-booking-enrollment-fence-v2"))
  }

  @Test def enrollmentRequiresTheExactPreviewedAutomaticMonitorSet(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    jdbc.update("INSERT INTO monitoring(record_id,account_id,active,autobook) VALUES (10,1,TRUE,TRUE)")
    jdbc.update("INSERT INTO monitoring(record_id,account_id,active,autobook) VALUES (11,1,TRUE,TRUE)")
    jdbc.update("INSERT INTO monitoring(record_id,account_id,active,autobook) VALUES (12,1,TRUE,FALSE)")
    jdbc.update("INSERT INTO monitoring(record_id,account_id,active,autobook) VALUES (13,2,TRUE,TRUE)")
    val monitorings = mock(classOf[MonitoringService])
    val controller = controllerWith(service, monitorings, smartEnrolled = false)
    assertEquals(409, controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(List(10L))).getStatusCode.value())
    assertFalse(service.smartBookingEnrolled(1L))
    assertEquals(2L, jdbc.queryForObject("SELECT COUNT(*) FROM monitoring WHERE account_id=1 AND active=TRUE AND autobook=TRUE", classOf[java.lang.Long]))
    assertEquals(409, controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(List(11L, 10L))).getStatusCode.value())
    assertFalse(service.smartBookingEnrolled(1L))

    val response = controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(List(10L, 11L)))
    assertEquals(200, response.getStatusCode.value())
    val enrolled = response.getBody.asInstanceOf[ApiResponse[SmartBookingEnrollment]].data.get
    assertEquals(Seq(10L, 11L), enrolled.stoppedAutoMonitorIds)
    assertTrue(service.smartBookingEnrolled(1L))
    assertFalse(service.canLegacyMonitorBook(1L, 10L))
    assertEquals(0L, jdbc.queryForObject("SELECT COUNT(*) FROM monitoring WHERE account_id=1 AND active=TRUE AND autobook=TRUE", classOf[java.lang.Long]))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM monitoring WHERE account_id=1 AND active=TRUE AND autobook=FALSE", classOf[java.lang.Long]))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM monitoring WHERE account_id=2 AND active=TRUE AND autobook=TRUE", classOf[java.lang.Long]))
  }

  @Test def enrolledAccountCannotCreateAnotherAutomaticMonitor(): Unit = {
    val service = fixture()
    service.enrollSmartBooking(1L)
    val monitoringService = new MonitoringService()
    for ((name, value) <- List(
      "bookingFence" -> new AccountBookingFence(),
      "bookingAttempts" -> service
    )) {
      val field = classOf[MonitoringService].getDeclaredField(name)
      field.setAccessible(true)
      field.set(monitoringService, value)
    }
    val monitoring = new Monitoring()
    monitoring.accountId = 1L
    monitoring.autobook = true
    val rejected = assertThrows(classOf[BookingRejectedException], () => monitoringService.createMonitoring(monitoring))
    assertEquals("SMART_BOOKING_ENROLLED", rejected.code)
  }

  @Test def smartAttemptNeedsDurableEnrollmentMarker(): Unit = {
    val service = fixture()
    val controller = controllerWith(service, mock(classOf[MonitoringService]), smartEnrolled = false)
    val req = request().copy(isImpediment = Some(false))
    val outcome = controller.submitBookingAttempt(1L, req).getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals(Some("SMART_BOOKING_NOT_ENROLLED"), outcome.errorCode)
    assertFalse(service.accountBusy(1L))
  }

  @Test def duplicateNormalizedLuxmedIdentityCannotBeEnrolled(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    jdbc.update("INSERT INTO credentials(account_id,username) VALUES (?,?)", Long.box(2L), " PERSON@EXAMPLE.COM ")
    val controller = controllerWith(service, mock(classOf[MonitoringService]), smartEnrolled = false)
    assertEquals(409, controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(Nil)).getStatusCode.value())
    assertFalse(service.smartBookingEnrolled(1L))
    assertFalse(service.smartBookingIdentitySafe(1L))
  }

  @Test def aliasCreatedAfterEnrollmentCannotBookOrPreserveSmartEligibility(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val controller = controllerWith(service, mock(classOf[MonitoringService]))
    jdbc.update("INSERT INTO credentials(account_id,username) VALUES (?,?)", Long.box(2L), "PERSON@example.com")
    assertFalse(service.smartBookingIdentitySafe(1L))
    assertTrue(service.identityHasSmartEnrollment(2L))
    assertFalse(service.canLegacyMonitorBook(2L, 10L))
    assertEquals(409, controller.bookAppointment(2L, request().copy(attemptId = None)).getStatusCode.value())
    val outcome = controller.submitBookingAttempt(1L, request().copy(isImpediment = Some(false)))
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals(Some("SMART_BOOKING_IDENTITY_UNSAFE"), outcome.errorCode)
  }

  @Test def enrolledAccountRemainsFencedAfterItsUsernameChanges(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val controller = controllerWith(service, mock(classOf[MonitoringService]))
    jdbc.update("UPDATE credentials SET username=? WHERE account_id=?", "other@example.com", Long.box(1L))
    assertTrue(service.identityHasSmartEnrollment(1L))
    assertFalse(service.smartBookingIdentitySafe(1L))
    assertEquals(409, controller.enrollSmartBooking(1L, SmartBookingEnrollmentRequest(Nil)).getStatusCode.value())
    assertEquals(409, controller.bookAppointment(1L, request().copy(attemptId = None)).getStatusCode.value())
  }

  @Test def newChatCannotLinkAnAlreadyEnrolledLuxmedIdentity(): Unit = {
    val service = fixture()
    service.enrollSmartBooking(1L)
    val data = new DataService()
    val repository = mock(classOf[DataRepository])
    when(repository.findUserIdBySource("new-chat", 3L)).thenReturn(None)
    for ((name, value) <- List("bookingAttempts" -> service, "dataRepository" -> repository)) {
      val field = classOf[DataService].getDeclaredField(name)
      field.setAccessible(true)
      field.set(data, value)
    }
    val source = MessageSource(MessageSourceSystem(3L), "new-chat")
    assertThrows(classOf[BookingRejectedException], () => data.saveCredentials(source, "PERSON@EXAMPLE.COM", "encrypted"))
  }

  @Test def earlyValidationFailuresHaveRecoverableReceipts(): Unit = {
    val service = fixture()
    val controller = controllerWith(service, mock(classOf[MonitoringService]))
    val impeded = request()
    val first = controller.submitBookingAttempt(1L, impeded).getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals(Some("IMPEDIMENT_REQUIRES_REVIEW"), first.errorCode)
    assertEquals(first, service.status(1L, impeded.attemptId.get).get)
    val unprepared = request().copy(isImpediment = Some(false), isPreparationRequired = true)
    val second = controller.submitBookingAttempt(1L, unprepared).getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals(Some("PREPARATION_MISSING"), second.errorCode)
    assertEquals(second, service.status(1L, unprepared.attemptId.get).get)
    assertFalse(service.accountBusy(1L))
  }

  @Test def smartReplacementIsRejectedBeforeAnyProviderBookingCall(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val controller = controllerWith(service, mock(classOf[MonitoringService]), api)
    val replacement = request().copy(isImpediment = Some(false), rebookIfExists = true)
    val outcome = controller.submitBookingAttempt(1L, replacement)
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals("failed", outcome.state)
    assertEquals(Some("SMART_REBOOK_REQUIRES_REVIEW"), outcome.errorCode)
    assertEquals(outcome, service.status(1L, replacement.attemptId.get).get)
    assertFalse(service.accountBusy(1L))
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).getXsrfToken(anyLong())
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationLockterm(anyLong(), any(), any())
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationConfirm(anyLong(), any(), any(), any())
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationChangeTerm(anyLong(), any(), any(), any())
  }

  @Test def lockBusinessErrorsAndUnapprovedReplacementPreventConfirmation(): Unit = {
    val value = ReservationLocktermResponseValue(true, None, null, Nil, 123, Nil)
    val response = ReservationLocktermResponse(Nil, Nil, false, false, value)
    assertTrue(BookingAttemptService.validateLockterm(response, false).isLeft)
    assertTrue(BookingAttemptService.validateLockterm(response, true).isLeft)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val withValuation = response.copy(value = value.copy(valuations = List(valuation)))
    assertTrue(BookingAttemptService.validateLockterm(withValuation.copy(value = withValuation.value.copy(valuations = List(valuation.copy(price = Some(25.0))))), false).isLeft)
    assertTrue(BookingAttemptService.validateLockterm(withValuation.copy(value = withValuation.value.copy(valuations = List(valuation.copy(isReferralRequired = true)))), false).isLeft)
    assertTrue(BookingAttemptService.validateLockterm(withValuation, true).isLeft)
    assertTrue(BookingAttemptService.validateLockterm(withValuation.copy(value = withValuation.value.copy(changeTermAvailable = false)), false).isRight)
    val related = RelatedVisit(null, "Clinic", false, 77, LocalTime.NOON, LocalTime.NOON.plusMinutes(30))
    assertTrue(BookingAttemptService.validateLockterm(withValuation.copy(value = withValuation.value.copy(relatedVisits = List(related))), true).isRight)
    assertTrue(BookingAttemptService.validateLockterm(response.copy(hasErrors = true), true).isLeft)
    assertTrue(BookingAttemptService.validateLockterm(response.copy(value = null), true).isLeft)
    val service = fixture()
    val outcome = service.execute(1, request())(() => Left(new BookingRejectedException("ALREADY_RESERVED")))
    assertEquals(Some("ALREADY_RESERVED"), outcome.errorCode)
    assertEquals("succeeded", service.execute(1, request())(() => Right(success)).state)
  }

  @Test def v1LegacyAcknowledgementAcceptsOneSucceededBarrierWithOrWithoutAnOldLock(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val newId = service.beginLegacyBooking(1L, 1791288000000L)
    service.completeLegacyBooking(1L, newId, 77L)
    assertTrue(service.acknowledgeLegacyBookingV1(1L, 77L))
    assertFalse(service.accountBusy(1L))
    val oldId = UUID.randomUUID().toString
    jdbc.update("INSERT INTO legacy_booking_barrier(id,account_id,state,reservation_id,start_at,created_at) " +
      "VALUES (?,1,'succeeded',88,1791288000000,1)", oldId)
    assertTrue(service.accountBusy(1L), "old unbackfilled barriers still block new submissions")
    assertTrue(service.acknowledgeLegacyBookingV1(1L, 88L))
    assertFalse(service.accountBusy(1L))
  }

  @Test def matchingReservationIdWithMovedTimeOrClinicInvalidatesThreeDayBaseline(): Unit = {
    val start = 1791288000000L
    val zone = ZoneId.of("Europe/Warsaw")
    def event(at: Long, clinicId: Long, end: Option[Long] = Some(1791289800000L)): Event =
      Event(ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(at), zone),
        Some(EventClinic("Street", "Warsaw", Some(clinicId))), None, 42L, "Reserved", "Visit",
        end.map(value => ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(value), zone)), Some("Visit"))
    val baseline = ReservationBaselineFact(42L, start, start + 1800000L,
      Some(2L), false, Some("Street"), Some("Warsaw"))
    val req = request().copy(baselineReservationIds = Some(List(42L)), baselineReservations = Some(List(baseline)))
    val from = start - 86400000L
    val to = start + 172800000L
    assertTrue(BookingAttemptService.verifyReservationBaseline(req, List(event(start, 2L)), from, to).isRight)
    assertTrue(BookingAttemptService.verifyReservationBaseline(req,
      List(event(start - 3600000L, 2L, Some(start - 1800000L))), from, to).isLeft)
    assertTrue(BookingAttemptService.verifyReservationBaseline(req, List(event(start, 3L)), from, to).isLeft)
    assertTrue(BookingAttemptService.verifyReservationBaseline(req, List(event(start, 2L, None)), from, to).isLeft)
    assertTrue(BookingAttemptService.verifyReservationBaseline(req, Nil, from, to).isLeft)
    assertTrue(BookingAttemptService.recoveryFacts(req.copy(baselineReservationIds = Some(List(42L, 99L)))).nonEmpty,
      "exact facts may cover only the three-day window while recovery IDs cover the whole snapshot")
  }

  @Test def liveMovedReservationBlocksConfirmationBeforeProviderCall(): Unit = {
    val service = fixture()
    val api = mock(classOf[ApiService])
    val monitorings = mock(classOf[MonitoringService])
    when(monitorings.getActiveMonitorings(1L)).thenReturn(Seq.empty)
    val controller = controllerWith(service, monitorings, api)
    val valuation = Valuation(None, None, false, false, None, Some(0.0), None, None, None, false, 1)
    val lock = ReservationLocktermResponse(Nil, Nil, false, false,
      ReservationLocktermResponseValue(false, None, null, Nil, 123L, List(valuation)))
    when(api.getXsrfToken(anyLong())).thenReturn(Right(XsrfToken("tok", Seq.empty)))
    when(api.reservationLockterm(anyLong(), any(), any())).thenReturn(Right(lock))
    val start = ZonedDateTime.of(2026, 10, 6, 12, 0, 0, 0, ZoneId.of("Europe/Warsaw"))
    val baseline = ReservationBaselineFact(42L, start.toInstant.toEpochMilli, start.plusMinutes(30).toInstant.toEpochMilli,
      Some(2L), false, Some("Street"), Some("Warsaw"))
    val moved = Event(start.minusHours(1), Some(EventClinic("Street", "Warsaw", Some(2L))), None,
      42L, "Reserved", "Visit", Some(start.minusMinutes(30)), Some("Visit"))
    when(api.reservedVerified(anyLong(), any(), any())).thenReturn(Right(List(moved)))
    val req = request().copy(isImpediment = Some(false), baselineReservationIds = Some(List(42L)),
      baselineReservations = Some(List(baseline)))
    val outcome = controller.submitBookingAttempt(1L, req)
      .getBody.asInstanceOf[ApiResponse[BookingOutcome]].data.get
    assertEquals("failed", outcome.state)
    assertEquals(Some("RESERVATION_SNAPSHOT_CHANGED"), outcome.errorCode)
    org.mockito.Mockito.verify(api, org.mockito.Mockito.never()).reservationConfirm(anyLong(), any(), any(), any())
    assertFalse(service.accountBusy(1L))
  }

  @Test def cancelledReviewRequiresAbsenceAndSettledProviderBeforeReleasingAccount(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val start = 1791288000000L
    val present = List(Event(ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(start + 86400000L), ZoneId.of("Europe/Warsaw")),
      None, None, 77L, "Reserved", "Visit"))
    service.beginCancellation(1L, 77L, start)
    assertThrows(classOf[BookingRejectedException], () => service.reviewCancellation(1L, 77L, start,
      "confirmed_cancelled", "operator", "Checked portal", false, true, None, Nil))
    assertThrows(classOf[BookingRejectedException], () => service.reviewCancellation(1L, 77L, start,
      "confirmed_cancelled", "operator", "Checked portal", true, false, None, Nil))
    assertThrows(classOf[BookingRejectedException], () => service.reviewCancellation(1L, 77L, start,
      "confirmed_cancelled", "operator", "Checked portal", true, true, None, present))
    assertTrue(service.accountBusy(1L))
    assertEquals("confirmed", service.reviewCancellation(1L, 77L, start,
      "confirmed_cancelled", "operator", "Checked portal", true, true, None, Nil).state)
    assertFalse(service.accountBusy(1L))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit " +
      "WHERE reservation_id=77 AND provider_request_settled=TRUE", classOf[java.lang.Long]))
  }

  @Test def verifiedMoveKeepsAccountHeldUntilExactBotAcknowledgement(): Unit = {
    val (service, jdbc) = fixtureWithDb()
    val original = 1791288000000L
    val moved = original + 86400000L
    val zone = ZoneId.of("Europe/Warsaw")
    val newVisit = Event(ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(moved), zone),
      Some(EventClinic("Street 1", "Warsaw", Some(23L))), None, 77L, "Reserved", "Visit",
      Some(ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(moved + 1800000L), zone)), Some("Visit"))
    service.beginCancellation(1L, 77L, original)
    assertThrows(classOf[BookingRejectedException], () => service.reviewCancellation(1L, 77L, original,
      "verified_moved", "operator", "Moved in portal", true, false, Some(moved),
      List(newVisit.copy(dateTo = None))))
    assertThrows(classOf[BookingRejectedException], () => service.reviewCancellation(1L, 77L, original,
      "verified_moved", "operator", "Moved in portal", true, false, Some(moved),
      List(newVisit, newVisit.copy(date = ZonedDateTime.ofInstant(java.time.Instant.ofEpochMilli(original), zone)))))
    assertTrue(service.cancellationPending(1L))
    val reviewed = service.reviewCancellation(1L, 77L, original,
      "verified_moved", "operator", "Moved in portal", true, false, Some(moved), List(newVisit))
    assertEquals("verified_moved", reviewed.state)
    assertEquals(Some(moved), reviewed.movedStartAt)
    assertEquals(Some(moved + 1800000L), reviewed.movedEndAt)
    assertEquals(Some(23L), reviewed.movedClinicId)
    assertTrue(service.accountBusy(1L))
    assertFalse(service.acknowledgeMovedCancellation(1L, 77L, original, moved + 60000L))
    assertTrue(service.accountBusy(1L))
    assertTrue(service.acknowledgeMovedCancellation(1L, 77L, original, moved))
    assertTrue(service.acknowledgeMovedCancellation(1L, 77L, original, moved))
    assertFalse(service.accountBusy(1L))
    assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM cancellation_receipt_review_audit " +
      "WHERE reservation_id=77 AND moved_start_at=? AND moved_acknowledged_at IS NOT NULL",
      classOf[java.lang.Long], Long.box(moved)))
  }
}
